# Generated by Django 5.0.6 on 2024-07-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='walletaddress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='address',
            field=models.CharField(default='hsjdkldjskjljs', max_length=255),
        ),
        migrations.RemoveField(
            model_name='walletaddress',
            name='user',
        ),
    ]
