# Generated by Django 5.0.6 on 2024-07-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_minimumamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='withdraw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
