# Generated by Django 5.0.6 on 2024-07-10 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_balance_bch_balance_alter_balance_btc_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawtransaction',
            name='wallet_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
