# Generated by Django 5.0.6 on 2024-07-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_withdrawtransaction_wallet_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('USD', 'USD Investment Plan'), ('ETH', 'ETH Investment Plan'), ('BTC', 'BTC Investment Plan'), ('LTC', 'LTC Investment Plan'), ('TRX', 'TRX Investment Plan'), ('BCH', 'BCH Investment Plan')], max_length=3, unique=True)),
                ('investment_amount_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_amount_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_profit_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_profit_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_min_months', models.IntegerField()),
                ('duration_max_months', models.IntegerField()),
            ],
        ),
    ]
