# Generated by Django 5.0.6 on 2024-07-23 16:58

from django.db import migrations



def populate_investment_plans(apps, schema_editor):
    InvestmentPlan = apps.get_model('accounts', 'InvestmentPlan')
    plans = [
        {
            'plan_type': 'USD',
            'investment_amount_min': 1000.00,
            'investment_amount_max': 50000.00,
            'expected_profit_min': 5.00,
            'expected_profit_max': 7.00,
            'duration_min_months': 3,
            'duration_max_months': 12,
        },
        {
            'plan_type': 'ETH',
            'investment_amount_min': 3000.00,
            'investment_amount_max': 75000.00,
            'expected_profit_min': 10.00,
            'expected_profit_max': 15.00,
            'duration_min_months': 6,
            'duration_max_months': 12,
        },
        {
            'plan_type': 'BTC',
            'investment_amount_min': 5000.00,
            'investment_amount_max': 100000.00,
            'expected_profit_min': 8.00,
            'expected_profit_max': 12.00,
            'duration_min_months': 6,
            'duration_max_months': 12,
        },
        {
            'plan_type': 'LTC',
            'investment_amount_min': 2000.00,
            'investment_amount_max': 60000.00,
            'expected_profit_min': 7.00,
            'expected_profit_max': 10.00,
            'duration_min_months': 6,
            'duration_max_months': 12,
        },
        {
            'plan_type': 'TRX',
            'investment_amount_min': 1500.00,
            'investment_amount_max': 40000.00,
            'expected_profit_min': 5.00,
            'expected_profit_max': 8.00,
            'duration_min_months': 3,
            'duration_max_months': 12,
        },
        {
            'plan_type': 'BCH',
            'investment_amount_min': 2500.00,
            'investment_amount_max': 70000.00,
            'expected_profit_min': 6.00,
            'expected_profit_max': 9.00,
            'duration_min_months': 6,
            'duration_max_months': 12,
        },
    ]

    for plan in plans:
        InvestmentPlan.objects.create(**plan)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_investmentplan'),
    ]

    operations = [
        migrations.RunPython(populate_investment_plans),
    ]

