# Generated by Django 5.0.6 on 2024-07-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_populate_investment_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('EUR/USD', 'EUR/USD Plan'), ('USD/JPY', 'USD/JPY Plan'), ('GBP/USD', 'GBP/USD Plan'), ('USD/CAD', 'USD/CAD Plan')], max_length=20, unique=True)),
                ('investment_amount_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_amount_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_profit_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_profit_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_min_months', models.IntegerField()),
                ('duration_max_months', models.IntegerField()),
            ],
        ),
    ]
