# Generated by Django 5.0.6 on 2024-07-23 17:13

from django.db import migrations


def populate_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    plans = [
        {
            'plan_name': 'EUR/USD',
            'investment_amount_min': 5000.00,
            'investment_amount_max': 100000.00,
            'expected_profit_min': 8.00,
            'expected_profit_max': 12.00,
            'duration_min_months': 6,
            'duration_max_months': 12,
        },
        {
            'plan_name': 'USD/JPY',
            'investment_amount_min': 3000.00,
            'investment_amount_max': 75000.00,
            'expected_profit_min': 10.00,
            'expected_profit_max': 15.00,
            'duration_min_months': 6,
            'duration_max_months': 12,
        },
        {
            'plan_name': 'GBP/USD',
            'investment_amount_min': 1000.00,
            'investment_amount_max': 50000.00,
            'expected_profit_min': 5.00,
            'expected_profit_max': 7.00,
            'duration_min_months': 3,
            'duration_max_months': 12,
        },
        {
            'plan_name': 'USD/CAD',
            'investment_amount_min': 2000.00,
            'investment_amount_max': 60000.00,
            'expected_profit_min': 7.00,
            'expected_profit_max': 10.00,
            'duration_min_months': 6,
            'duration_max_months': 12,
        },
    ]

    for plan in plans:
        SubscriptionPlan.objects.create(**plan)



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subscriptionplan'),
    ]

    operations = [
         migrations.RunPython(populate_subscription_plans),
    ]
