# Generated by Django 5.0.7 on 2024-08-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_subscription_investment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_subscription_investment',
            old_name='Sub_investment_plan',
            new_name='investment_plan',
        ),
    ]
