# Generated by Django 5.0.7 on 2024-08-03 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_sub_investment_plan_user_subscription_investment_investment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_subscription_investment',
            name='investment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptionplan'),
        ),
    ]
